import { Platform } from "react-native";
import {
  PHONEPE_MERCHANT_ID,
  PHONEPE_APP_ID,
  PHONEPE_ENV,
  PHONEPE_ENABLE_LOGS,
} from "@/lib/config";

/**
 * Interface representing the react-native-phonepe-pg SDK.
 */
interface PhonePeSDKModule {
  init(
    environment: string,
    merchantId: string,
    appId: string | null,
    enableLogs: boolean,
  ): Promise<boolean>;
  startTransaction(
    base64Body: string,
    checksum: string,
    packageName: string | null,
    callbackURL: string | null,
  ): Promise<{ status: string; error?: string }>;
}

let PhonePeSDK: PhonePeSDKModule | null = null;

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require("react-native-phonepe-pg");
  PhonePeSDK = mod.default || mod;
} catch {
  PhonePeSDK = null;
}

/**
 * Checks whether the PhonePe Native SDK is available in the current runtime environment.
 * Returns false when running in Expo Go or Web, where custom native modules cannot execute.
 */
export function isPhonePeNativeAvailable(): boolean {
  return (
    Platform.OS !== "web" &&
    PhonePeSDK !== null &&
    typeof PhonePeSDK.init === "function" &&
    typeof PhonePeSDK.startTransaction === "function"
  );
}

let isInitialized = false;
let currentMerchant = "";

/**
 * Initializes the PhonePe SDK with the configured merchant credentials.
 */
export async function initPhonePeSDK(
  merchantId?: string,
  environment?: "SANDBOX" | "PRODUCTION",
): Promise<boolean> {
  if (!isPhonePeNativeAvailable() || !PhonePeSDK) {
    return false;
  }

  const mid = merchantId || PHONEPE_MERCHANT_ID;
  const env = environment || PHONEPE_ENV;

  if (isInitialized && currentMerchant === mid) {
    return true;
  }

  try {
    const success = await PhonePeSDK.init(
      env,
      mid,
      PHONEPE_APP_ID || null,
      PHONEPE_ENABLE_LOGS,
    );
    isInitialized = true;
    currentMerchant = mid;
    return success;
  } catch (error) {
    console.warn("[PhonePe] SDK initialization failed:", error);
    return false;
  }
}

export type PhonePeTransactionResult = {
  status: "SUCCESS" | "FAILURE" | "UNAVAILABLE";
  error?: string;
};

/**
 * Starts a native PhonePe transaction.
 *
 * @param params Transaction payload generated by POST /api/v1/payments/phonepe/initiate-sdk
 */
export async function startPhonePeTransaction(params: {
  merchantId: string;
  base64Body: string;
  checksum: string;
  environment?: "SANDBOX" | "PRODUCTION";
}): Promise<PhonePeTransactionResult> {
  if (!isPhonePeNativeAvailable() || !PhonePeSDK) {
    return {
      status: "UNAVAILABLE",
      error: "PhonePe native SDK is not available in this build (requires a development build).",
    };
  }

  const initialized = await initPhonePeSDK(params.merchantId, params.environment);
  if (!initialized) {
    return {
      status: "FAILURE",
      error: "Failed to initialize PhonePe SDK.",
    };
  }

  try {
    // On iOS, pass app schema so UPI apps can redirect back to Diva app
    const appSchema = Platform.OS === "ios" ? "diva" : null;

    const response = await PhonePeSDK.startTransaction(
      params.base64Body,
      params.checksum,
      appSchema,
      null,
    );

    const isSuccess =
      response?.status === "SUCCESS" ||
      (typeof response === "string" && response === "SUCCESS");

    return {
      status: isSuccess ? "SUCCESS" : "FAILURE",
      error: response?.error,
    };
  } catch (cause: unknown) {
    const message = cause instanceof Error ? cause.message : String(cause);
    console.warn("[PhonePe] Transaction finished with error/cancelled:", message);
    return {
      status: "FAILURE",
      error: message,
    };
  }
}
